[project]
name = "waveletnn"
version = "0.1.0"
description = ""
authors = [
    {name = "Scurrra (Ilja Baroŭski)",email = "iscurrra@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch (>=2.5.1)",
    "numpy"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
